import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createShippingHandler} from './backend-shipping.mjs';
const productId='gid://shopify/Product/16132811981134',id='gid://shopify/ProductVariant/123';
function fixture(change=()=>{}){
 const variant={id,sku:'autods-sku',availableForSale:true,quantityAvailable:10,price:{amount:'64.63',currencyCode:'EUR'},product:{id:productId,tags:['country-germany','store-home']}};
 const data={shop:{fulfillmentServices:[{serviceName:'AutoDS prod-fizmvhfr',location:{id:'autods-location'}}]},node:{id,sku:variant.sku,product:{id:productId,status:'ACTIVE'},contextualPricing:{price:variant.price},deliveryProfile:{id:'gid://shopify/DeliveryProfile/147908591950',default:false,coversAllItems:false,profileLocationGroups:[{locationGroup:{locations:{nodes:[{id:'autods-location'}],pageInfo:{hasNextPage:false}}},locationGroupZones:{nodes:[{zone:{countries:[{code:{countryCode:'DE',restOfWorld:false}}]},methodDefinitions:{nodes:[{active:true,name:'Shipping included',methodConditions:[],rateProvider:{price:{amount:'0.00',currencyCode:'EUR'}}}],pageInfo:{hasNextPage:false}}}],pageInfo:{hasNextPage:false}}}]}}};
 change({variant,data});let reads=0;
 const db={get:async()=>null,getWithMetadata:async()=>null,setJSON:async()=>({modified:true})};
 const handler=createShippingHandler({storefrontConfig:{domain:'example.myshopify.com',apiVersion:'2026-10',publicToken:'public'},env:{},dbFactory:async()=>db,autodsAdminFactory:()=>async()=>{reads++;return data;},fetcher:async url=>{assert.ok(url.includes('myshopify.com'),'Never contact CJ for AutoDS');return Response.json({data:{node:variant}});}});
 const run=async suffix=>{const response=await handler(new Request('https://vizimall.com/api/shipping?'+new URLSearchParams({variant:id,country:'DE',shipping:'DE',store:'home',...suffix})));return {status:response.status,quote:await response.json()};};
 return {run,variant,data,reads:()=>reads};
}
test('AutoDS returns current Shopify prices, combined business-day estimate and quantity totals without CJ credentials',async()=>{const f=fixture(),{quote}=await f.run({quantity:'3'});assert.equal(quote.status,'available');assert.equal(quote.pricing.checkoutReady,true);assert.equal(quote.pricing.lineTotal.amount,'193.89');assert.equal(quote.stockQuantity,10);assert.deepEqual(quote.totalDelivery,{days:7,unit:'business_days',includesProcessing:true});});
test('AutoDS discovery confirms only Germany',async()=>{assert.deepEqual((await fixture().run({check:'destinations',cached:'1'})).quote.destinations,['DE']);});
test('AutoDS rejects non-German delivery and excessive quantities',async()=>{const f=fixture();for(const input of [{shipping:'GR'},{country:'FR'},{quantity:'11'}])assert.equal((await f.run(input)).quote.status,'unavailable');assert.equal(f.reads(),0);});
test('Stock and price changes are rechecked for later requests',async()=>{const f=fixture();assert.equal((await f.run({})).quote.status,'available');f.variant.quantityAvailable=0;assert.equal((await f.run({})).quote.status,'unavailable');f.variant.quantityAvailable=10;f.variant.price={amount:'65.00',currencyCode:'EUR'};assert.equal((await f.run({})).quote.status,'unavailable');});
test('Unverified products cannot use the AutoDS bridge',async()=>{assert.equal((await fixture(({variant})=>{variant.product.id='gid://shopify/Product/999';}).run({})).quote.status,'not_mapped');});
test('Changed shipping zones, conditional or paid rates and incomplete profiles fail closed',async()=>{for(const alter of [z=>{z.zone.countries[0].code.countryCode='FR';},z=>{z.zone.countries.push({code:{countryCode:'GR'}});},z=>{z.methodDefinitions.nodes[0].rateProvider.price.amount='2.00';},z=>{z.methodDefinitions.nodes[0].methodConditions=[{}];},z=>{z.methodDefinitions.pageInfo.hasNextPage=true;}]){const f=fixture(({data})=>alter(data.node.deliveryProfile.profileLocationGroups[0].locationGroupZones.nodes[0]));assert.equal((await f.run({})).quote.status,'unavailable');}});
test('Missing AutoDS ownership, mixed country tags and archived products fail closed',async()=>{for(const alter of [({data})=>{data.shop.fulfillmentServices=[];},({variant})=>{variant.product.tags.push('country-france');},({data})=>{data.node.product.status='ARCHIVED';}])assert.equal((await fixture(alter).run({})).quote.status,'unavailable');});
