(function(root){
  'use strict';
  const rows=`
Bag ({count})|Warenkorb ({count})|Καλάθι ({count})|Panier ({count})|Carrello ({count})|Cesta ({count})|Tas ({count})|Koszyk ({count})|Carrinho ({count})
Your bag · Shipping to {place}|Ihr Warenkorb · Lieferung nach {place}|Το καλάθι σας · Αποστολή σε {place}|Votre panier · Livraison vers {place}|Il tuo carrello · Spedizione a {place}|Tu cesta · Envío a {place}|Je tas · Verzending naar {place}|Twój koszyk · Dostawa do {place}|O seu carrinho · Envio para {place}
Estimated subtotal: {price}|Geschätzte Zwischensumme: {price}|Εκτιμώμενο υποσύνολο: {price}|Sous-total estimé : {price}|Subtotale stimato: {price}|Subtotal estimado: {price}|Geschat subtotaal: {price}|Szacowana suma: {price}|Subtotal estimado: {price}
Selected: {option}|Ausgewählt: {option}|Επιλογή: {option}|Sélection : {option}|Selezionato: {option}|Seleccionado: {option}|Geselecteerd: {option}|Wybrano: {option}|Selecionado: {option}
{count} remaining · selected option|{count} verfügbar · ausgewählte Option|{count} διαθέσιμα · επιλεγμένη επιλογή|{count} disponibles · option sélectionnée|{count} disponibili · opzione selezionata|{count} disponibles · opción seleccionada|{count} beschikbaar · geselecteerde optie|{count} dostępnych · wybrany wariant|{count} disponíveis · opção selecionada
{count} remaining in {place}|{count} verfügbar in {place}|{count} διαθέσιμα σε {place}|{count} disponibles en {place}|{count} disponibili in {place}|{count} disponibles en {place}|{count} beschikbaar in {place}|{count} dostępnych w {place}|{count} disponíveis em {place}
{count} delivery countries confirmed. Checking more…|{count} Lieferländer bestätigt. Weitere werden geprüft…|{count} χώρες επιβεβαιώθηκαν. Έλεγχος περισσότερων…|{count} pays confirmés. Vérification en cours…|{count} paesi confermati. Verifica in corso…|{count} países confirmados. Comprobando más…|{count} bezorglanden bevestigd. Meer controleren…|Potwierdzono {count} krajów. Sprawdzanie kolejnych…|{count} países confirmados. A verificar mais…
{count} products|{count} Produkte|{count} προϊόντα|{count} produits|{count} prodotti|{count} productos|{count} producten|{count} produktów|{count} produtos
Photo {index} of {count} · Click to enlarge|Foto {index} von {count} · Zum Vergrößern klicken|Φωτογραφία {index} από {count} · Πατήστε για μεγέθυνση|Photo {index} sur {count} · Cliquez pour agrandir|Foto {index} di {count} · Clicca per ingrandire|Foto {index} de {count} · Haz clic para ampliar|Foto {index} van {count} · Klik om te vergroten|Zdjęcie {index} z {count} · Kliknij, aby powiększyć|Fotografia {index} de {count} · Clique para ampliar
{price} · standard shipping included|{price} · Standardversand inbegriffen|{price} · περιλαμβάνεται η τυπική αποστολή|{price} · livraison standard incluse|{price} · spedizione standard inclusa|{price} · envío estándar incluido|{price} · standaardverzending inbegrepen|{price} · standardowa dostawa w cenie|{price} · envio padrão incluído
From {price}|Ab {price}|Από {price}|À partir de {price}|Da {price}|Desde {price}|Vanaf {price}|Od {price}|Desde {price}
The {place} collection|Die Kollektion aus {place}|Η συλλογή από {place}|La collection de {place}|La collezione di {place}|La colección de {place}|De collectie uit {place}|Kolekcja z {place}|A coleção de {place}
Browsing {place} mall. Change mall|Sie besuchen das Einkaufszentrum {place}. Einkaufszentrum wechseln|Βρίσκεστε στο εμπορικό κέντρο {place}. Αλλαγή|Vous visitez le centre {place}. Changer de centre|Stai visitando il centro {place}. Cambia centro|Visitas el centro de {place}. Cambiar centro|Je bezoekt het winkelcentrum {place}. Ander centrum kiezen|Oglądasz centrum {place}. Zmień centrum|Está no centro {place}. Mudar de centro
Ships within {hours} hours|Versand innerhalb von {hours} Stunden|Αποστολή εντός {hours} ωρών|Expédié sous {hours} heures|Spedito entro {hours} ore|Se envía en {hours} horas|Verzonden binnen {hours} uur|Wysyłka w ciągu {hours} godzin|Expedição em {hours} horas
{days} days; preparation is additional|{days} Tage; Vorbereitung zusätzlich|{days} ημέρες· επιπλέον χρόνος προετοιμασίας|{days} jours ; préparation en supplément|{days} giorni; preparazione aggiuntiva|{days} días; preparación adicional|{days} dagen; voorbereiding komt erbij|{days} dni; dodatkowy czas przygotowania|{days} dias; preparação adicional
CJ checked {time}. Preparation and transport are separate estimates.|CJ-Prüfung um {time}. Vorbereitung und Transport werden getrennt geschätzt.|Έλεγχος CJ στις {time}. Προετοιμασία και μεταφορά υπολογίζονται ξεχωριστά.|Vérification CJ à {time}. Préparation et transport sont estimés séparément.|Verificato da CJ alle {time}. Preparazione e trasporto sono stime separate.|CJ comprobó a las {time}. Preparación y transporte se estiman por separado.|CJ gecontroleerd om {time}. Voorbereiding en transport zijn aparte schattingen.|CJ sprawdziło o {time}. Przygotowanie i transport mają osobne szacunki.|Verificado pela CJ às {time}. Preparação e transporte são estimados separadamente.
CJ estimate for {count} item(s), checked {time}. Final checkout charge is not yet verified.|CJ-Schätzung für {count} Artikel, geprüft um {time}. Der endgültige Kassenbetrag ist noch nicht bestätigt.|Εκτίμηση CJ για {count} είδη, έλεγχος στις {time}. Το τελικό κόστος δεν επιβεβαιώθηκε ακόμη.|Estimation CJ pour {count} articles, vérifiée à {time}. Montant final non encore confirmé.|Stima CJ per {count} articoli, verificata alle {time}. Importo finale non ancora confermato.|Estimación CJ para {count} artículos, comprobada a las {time}. Importe final aún sin verificar.|CJ-schatting voor {count} artikelen, gecontroleerd om {time}. Eindbedrag nog niet bevestigd.|Szacunek CJ dla {count} sztuk, sprawdzony o {time}. Końcowa kwota nie jest jeszcze potwierdzona.|Estimativa CJ para {count} artigos, verificada às {time}. Valor final ainda não confirmado.
Essential storage keeps your bag, country choice and secure sign-in working. Optional visit measurement runs only if you agree. We do not use advertising trackers or collect email addresses from cookies.|Notwendige Speicherung ermöglicht Warenkorb, Länderwahl und sichere Anmeldung. Die optionale Besuchsmessung erfolgt nur mit Ihrer Zustimmung. Wir verwenden keine Werbe-Tracker und erfassen keine E-Mail-Adressen über Cookies.|Η απαραίτητη αποθήκευση υποστηρίζει το καλάθι, τη χώρα και την ασφαλή σύνδεση. Η προαιρετική μέτρηση λειτουργεί μόνο με συγκατάθεση. Δεν χρησιμοποιούμε διαφημιστική παρακολούθηση ούτε συλλέγουμε email από cookies.|Le stockage essentiel assure le panier, le pays et la connexion sécurisée. La mesure facultative nécessite votre accord. Aucun suivi publicitaire ni collecte d’adresses e-mail par cookies.|La memorizzazione essenziale consente carrello, paese e accesso sicuro. La misurazione facoltativa richiede il consenso. Nessun tracciamento pubblicitario o raccolta di email tramite cookie.|El almacenamiento esencial permite cesta, país y acceso seguro. La medición opcional requiere consentimiento. No usamos rastreadores publicitarios ni recogemos correos mediante cookies.|Essentiële opslag ondersteunt je tas, landkeuze en veilig inloggen. Optionele bezoekmeting werkt alleen met toestemming. We gebruiken geen advertentietrackers en verzamelen geen e-mailadressen via cookies.|Niezbędne dane umożliwiają koszyk, wybór kraju i bezpieczne logowanie. Opcjonalny pomiar wymaga zgody. Nie używamy śledzenia reklam ani nie zbieramy adresów e-mail przez cookies.|O armazenamento essencial permite carrinho, país e início de sessão seguro. A medição opcional requer consentimento. Não usamos rastreadores publicitários nem recolhemos emails através de cookies.
Essential storage: always on for requested shopping and privacy preferences.|Notwendige Speicherung: für Einkäufe und Datenschutzeinstellungen immer aktiv.|Απαραίτητη αποθήκευση: πάντα ενεργή για αγορές και προτιμήσεις απορρήτου.|Stockage essentiel : toujours actif pour les achats et la confidentialité.|Memorizzazione essenziale: sempre attiva per acquisti e privacy.|Almacenamiento esencial: siempre activo para compras y privacidad.|Essentiële opslag: altijd actief voor aankopen en privacy.|Niezbędne dane: zawsze aktywne dla zakupów i prywatności.|Armazenamento essencial: sempre ativo para compras e privacidade.
Email offers require a separate signup. Cookie acceptance does not subscribe you.|E-Mail-Angebote erfordern eine separate Anmeldung. Cookie-Zustimmung ist kein Abonnement.|Οι προσφορές email απαιτούν ξεχωριστή εγγραφή. Η αποδοχή cookies δεν σας εγγράφει.|Les offres par e-mail nécessitent une inscription séparée. Accepter les cookies ne vous abonne pas.|Le offerte via email richiedono un’iscrizione separata. Accettare i cookie non ti iscrive.|Las ofertas por correo requieren registro aparte. Aceptar cookies no te suscribe.|E-mailaanbiedingen vereisen aparte aanmelding. Cookies accepteren meldt je niet aan.|Oferty e-mail wymagają osobnego zapisu. Zgoda na cookies nie zapisuje do newslettera.|As ofertas por email exigem inscrição separada. Aceitar cookies não subscreve ofertas.
Optional measurement allowed. You can change this at any time.|Optionale Messung erlaubt. Sie können dies jederzeit ändern.|Η προαιρετική μέτρηση επιτρέπεται. Αλλάξτε την επιλογή οποτεδήποτε.|Mesure facultative autorisée. Ce choix peut être modifié à tout moment.|Misurazione facoltativa consentita. Puoi modificare la scelta quando vuoi.|Medición opcional permitida. Puedes cambiarlo cuando quieras.|Optionele meting toegestaan. Je kunt dit altijd wijzigen.|Opcjonalny pomiar włączony. Możesz zmienić ustawienie w każdej chwili.|Medição opcional permitida. Pode alterar a qualquer momento.
Optional measurement off. Shopping remains available.|Optionale Messung deaktiviert. Einkaufen bleibt möglich.|Προαιρετική μέτρηση ανενεργή. Οι αγορές παραμένουν διαθέσιμες.|Mesure facultative désactivée. Les achats restent disponibles.|Misurazione facoltativa disattivata. Gli acquisti restano disponibili.|Medición opcional desactivada. Las compras siguen disponibles.|Optionele meting uit. Winkelen blijft beschikbaar.|Opcjonalny pomiar wyłączony. Zakupy nadal dostępne.|Medição opcional desativada. As compras continuam disponíveis.
A WORLD TO EXPLORE|EINE WELT ZUM ENTDECKEN|ΕΝΑΣ ΚΟΣΜΟΣ ΓΙΑ ΕΞΕΡΕΥΝΗΣΗ|UN MONDE À EXPLORER|UN MONDO DA ESPLORARE|UN MUNDO POR EXPLORAR|EEN WERELD OM TE ONTDEKKEN|ŚWIAT DO ODKRYCIA|UM MUNDO PARA EXPLORAR
Comfort for your home|Komfort für Ihr Zuhause|Άνεση για το σπίτι σας|Confort pour votre maison|Comfort per la tua casa|Comodidad para tu hogar|Comfort voor je huis|Komfort dla domu|Conforto para a sua casa
Care for yourself|Pflege für Sie|Φροντίδα για εσάς|Prenez soin de vous|Prenditi cura di te|Cuida de ti|Zorg voor jezelf|Zadbaj o siebie|Cuide de si
Smart everyday essentials|Smarte Alltagshelfer|Έξυπνα είδη καθημερινότητας|Les essentiels malins du quotidien|Essenziali intelligenti per ogni giorno|Esenciales inteligentes para cada día|Slimme dagelijkse benodigdheden|Praktyczne akcesoria na co dzień|Essenciais inteligentes para o dia a dia
Books, toys & little adventures|Bücher, Spielzeug & kleine Abenteuer|Βιβλία, παιχνίδια και μικρές περιπέτειες|Livres, jouets et petites aventures|Libri, giochi e piccole avventure|Libros, juguetes y pequeñas aventuras|Boeken, speelgoed en kleine avonturen|Książki, zabawki i małe przygody|Livros, brinquedos e pequenas aventuras
Accessories for every journey|Zubehör für jede Fahrt|Αξεσουάρ για κάθε διαδρομή|Accessoires pour chaque trajet|Accessori per ogni viaggio|Accesorios para cada viaje|Accessoires voor elke rit|Akcesoria na każdą podróż|Acessórios para cada viagem
Happy pets, happy homes|Glückliche Tiere, glückliches Zuhause|Χαρούμενα ζώα, χαρούμενα σπίτια|Animaux heureux, foyers heureux|Animali felici, case felici|Mascotas felices, hogares felices|Blije dieren, blije huizen|Szczęśliwe zwierzęta i domy|Animais felizes, lares felizes
UPSTAIRS|OBERGESCHOSS|ΕΠΑΝΩ ΟΡΟΦΟΣ|À L’ÉTAGE|PIANO SUPERIORE|PLANTA SUPERIOR|BOVENVERDIEPING|NA PIĘTRZE|PISO SUPERIOR
Upstairs|Obergeschoss|Επάνω όροφος|À l’étage|Piano superiore|Planta superior|Bovenverdieping|Na piętrze|Piso superior
Total for {count} item(s)|Gesamt für {count} Artikel|Σύνολο για {count} είδη|Total pour {count} articles|Totale per {count} articoli|Total de {count} artículos|Totaal voor {count} artikelen|Razem za {count} sztuk|Total para {count} artigos
Choose an option|Option wählen|Επιλέξτε επιλογή|Choisir une option|Scegli un’opzione|Elige una opción|Kies een optie|Wybierz wariant|Escolha uma opção
Try again|Erneut versuchen|Δοκιμάστε ξανά|Réessayer|Riprova|Inténtalo de nuevo|Probeer opnieuw|Spróbuj ponownie|Tentar novamente
Please try again.|Bitte versuchen Sie es erneut.|Δοκιμάστε ξανά.|Veuillez réessayer.|Riprova.|Inténtalo de nuevo.|Probeer opnieuw.|Spróbuj ponownie.|Tente novamente.
Checking availability and opening secure checkout…|Verfügbarkeit prüfen und sichere Kasse öffnen…|Έλεγχος διαθεσιμότητας και άνοιγμα ασφαλούς ταμείου…|Vérification de disponibilité et ouverture du paiement sécurisé…|Verifica disponibilità e apertura pagamento sicuro…|Comprobando disponibilidad y abriendo pago seguro…|Beschikbaarheid controleren en veilig afrekenen openen…|Sprawdzanie dostępności i otwieranie bezpiecznej płatności…|A verificar disponibilidade e abrir pagamento seguro…
Shipping cost and delivery time could not be verified. Please try again before checking out.|Versandkosten und Lieferzeit konnten nicht bestätigt werden. Bitte vor dem Bezahlen erneut versuchen.|Το κόστος και ο χρόνος αποστολής δεν επιβεβαιώθηκαν. Δοκιμάστε ξανά πριν πληρώσετε.|Frais et délai non confirmés. Réessayez avant de payer.|Costo e tempi non confermati. Riprova prima di pagare.|Coste y plazo sin confirmar. Reintenta antes de pagar.|Kosten en levertijd niet bevestigd. Probeer opnieuw voor je afrekent.|Koszt i czas dostawy niepotwierdzone. Spróbuj ponownie przed zapłatą.|Custo e prazo não confirmados. Tente novamente antes de pagar.
The shipping-included checkout price for this destination is not ready. Please try again later.|Der Preis inklusive Versand für dieses Lieferland ist noch nicht bereit. Bitte später erneut versuchen.|Η τιμή με αποστολή για αυτόν τον προορισμό δεν είναι έτοιμη. Δοκιμάστε αργότερα.|Le prix livraison comprise pour cette destination n’est pas prêt. Réessayez plus tard.|Prezzo con spedizione per questa destinazione non pronto. Riprova più tardi.|El precio con envío para este destino no está listo. Reintenta más tarde.|De prijs inclusief verzending voor deze bestemming is nog niet klaar. Probeer later opnieuw.|Cena z dostawą dla tego kierunku nie jest gotowa. Spróbuj później.|O preço com envio para este destino ainda não está pronto. Tente mais tarde.
This quantity exceeds the available stock or item limit.|Diese Menge überschreitet den Bestand oder das Artikellimit.|Η ποσότητα υπερβαίνει το απόθεμα ή το όριο.|Cette quantité dépasse le stock ou la limite.|La quantità supera le scorte o il limite.|La cantidad supera el stock o el límite.|Dit aantal overschrijdt de voorraad of limiet.|Ilość przekracza stan lub limit.|A quantidade excede o stock ou o limite.
Your bag is full. Please check out first.|Ihr Warenkorb ist voll. Bitte zuerst bezahlen.|Το καλάθι είναι γεμάτο. Ολοκληρώστε πρώτα την αγορά.|Votre panier est plein. Veuillez d’abord payer.|Il carrello è pieno. Completa prima il pagamento.|La cesta está llena. Finaliza primero la compra.|Je tas is vol. Reken eerst af.|Koszyk jest pełny. Najpierw dokończ zakup.|O carrinho está cheio. Finalize primeiro a compra.
Could not save. Please try again.|Speichern fehlgeschlagen. Bitte erneut versuchen.|Η αποθήκευση απέτυχε. Δοκιμάστε ξανά.|Enregistrement impossible. Réessayez.|Salvataggio non riuscito. Riprova.|No se pudo guardar. Reinténtalo.|Opslaan mislukt. Probeer opnieuw.|Nie zapisano. Spróbuj ponownie.|Não foi possível guardar. Tente novamente.
Loading reviews…|Bewertungen werden geladen…|Φόρτωση αξιολογήσεων…|Chargement des avis…|Caricamento recensioni…|Cargando reseñas…|Beoordelingen laden…|Ładowanie opinii…|A carregar avaliações…
Reviews unavailable|Bewertungen nicht verfügbar|Αξιολογήσεις μη διαθέσιμες|Avis indisponibles|Recensioni non disponibili|Reseñas no disponibles|Beoordelingen niet beschikbaar|Opinie niedostępne|Avaliações indisponíveis
Reviews currently unavailable|Bewertungen derzeit nicht verfügbar|Αξιολογήσεις προσωρινά μη διαθέσιμες|Avis actuellement indisponibles|Recensioni momentaneamente non disponibili|Reseñas temporalmente no disponibles|Beoordelingen momenteel niet beschikbaar|Opinie chwilowo niedostępne|Avaliações temporariamente indisponíveis
Show these products|Diese Produkte anzeigen|Εμφάνιση αυτών των προϊόντων|Afficher ces produits|Mostra questi prodotti|Mostrar estos productos|Deze producten tonen|Pokaż te produkty|Mostrar estes produtos
Try loading these products again|Diese Produkte erneut laden|Φόρτωση προϊόντων ξανά|Réessayer de charger ces produits|Ricarica questi prodotti|Reintentar cargar estos productos|Deze producten opnieuw laden|Załaduj produkty ponownie|Carregar estes produtos novamente
No products match this collection and these filters.|Keine Produkte passen zu dieser Kollektion und diesen Filtern.|Δεν βρέθηκαν προϊόντα με αυτά τα φίλτρα.|Aucun produit ne correspond à ces filtres.|Nessun prodotto corrisponde ai filtri.|No hay productos con estos filtros.|Geen producten met deze filters.|Brak produktów dla tych filtrów.|Nenhum produto corresponde aos filtros.
No products in this page match these prices.|Keine Produkte auf dieser Seite entsprechen diesen Preisen.|Κανένα προϊόν στη σελίδα με αυτές τις τιμές.|Aucun produit à ces prix sur cette page.|Nessun prodotto a questi prezzi nella pagina.|No hay productos a estos precios en esta página.|Geen producten met deze prijzen op deze pagina.|Brak produktów w tych cenach na stronie.|Nenhum produto com estes preços nesta página.
No matching products in this page. Load more to continue.|Keine passenden Produkte auf dieser Seite. Laden Sie weitere.|Κανένα αντίστοιχο προϊόν. Φορτώστε περισσότερα.|Aucun produit correspondant. Chargez la suite.|Nessun prodotto corrispondente. Caricane altri.|Sin productos coincidentes. Carga más.|Geen passende producten. Laad meer.|Brak pasujących produktów. Załaduj więcej.|Nenhum produto correspondente. Carregue mais.
Unable to load the next page. Please try again.|Nächste Seite konnte nicht geladen werden. Bitte erneut versuchen.|Η επόμενη σελίδα δεν φορτώθηκε. Δοκιμάστε ξανά.|Page suivante indisponible. Réessayez.|Pagina successiva non caricata. Riprova.|No se cargó la página siguiente. Reinténtalo.|Volgende pagina niet geladen. Probeer opnieuw.|Nie załadowano następnej strony. Spróbuj ponownie.|Não foi possível carregar a página seguinte. Tente novamente.
EXPLORE THE STORES ON THIS FLOOR|ENTDECKEN SIE DIE SHOPS AUF DIESER ETAGE|ΕΞΕΡΕΥΝΗΣΤΕ ΤΑ ΚΑΤΑΣΤΗΜΑΤΑ ΤΟΥ ΟΡΟΦΟΥ|EXPLOREZ LES BOUTIQUES DE CET ÉTAGE|ESPLORA I NEGOZI DI QUESTO PIANO|EXPLORA LAS TIENDAS DE ESTA PLANTA|ONTDEK DE WINKELS OP DEZE VERDIEPING|ODKRYJ SKLEPY NA TYM PIĘTRZE|EXPLORE AS LOJAS DESTE PISO
Home and Living|Wohnen & Leben|Σπίτι και διαβίωση|Maison et intérieur|Casa e arredamento|Hogar y decoración|Huis en wonen|Dom i wnętrze|Casa e decoração
Beauty and Care|Schönheit & Pflege|Ομορφιά και φροντίδα|Beauté et soins|Bellezza e cura|Belleza y cuidado|Beauty en verzorging|Uroda i pielęgnacja|Beleza e cuidados
Tech and Gadgets|Technik & Gadgets|Τεχνολογία και gadgets|Tech et gadgets|Tecnologia e gadget|Tecnología y gadgets|Tech en gadgets|Technologia i gadżety|Tecnologia e gadgets
Kids and Play|Kinder & Spielen|Παιδιά και παιχνίδι|Enfants et jeux|Bambini e giochi|Niños y juegos|Kinderen en spelen|Dzieci i zabawa|Crianças e brincadeiras
Auto and Accessories|Auto & Zubehör|Αυτοκίνητο και αξεσουάρ|Auto et accessoires|Auto e accessori|Auto y accesorios|Auto en accessoires|Auto i akcesoria|Auto e acessórios
Pets and Friends|Tiere & Freunde|Κατοικίδια και φίλοι|Animaux et amis|Animali e amici|Mascotas y amigos|Huisdieren en vrienden|Zwierzęta i przyjaciele|Animais e amigos
Welcome, {person}|Willkommen, {person}|Καλώς ήρθατε, {person}|Bienvenue, {person}|Benvenuto, {person}|Bienvenido, {person}|Welkom, {person}|Witaj, {person}|Bem-vindo, {person}
Your profile picture|Ihr Profilbild|Η φωτογραφία προφίλ σας|Votre photo de profil|La tua foto profilo|Tu foto de perfil|Je profielfoto|Twoje zdjęcie profilowe|A sua fotografia de perfil
Name saved to your Shopify account.|Name in Ihrem Shopify-Konto gespeichert.|Το όνομα αποθηκεύτηκε στο Shopify.|Nom enregistré dans votre compte Shopify.|Nome salvato nel tuo account Shopify.|Nombre guardado en tu cuenta Shopify.|Naam opgeslagen in je Shopify-account.|Imię zapisano na koncie Shopify.|Nome guardado na sua conta Shopify.
Profile picture saved.|Profilbild gespeichert.|Η φωτογραφία προφίλ αποθηκεύτηκε.|Photo de profil enregistrée.|Foto profilo salvata.|Foto de perfil guardada.|Profielfoto opgeslagen.|Zapisano zdjęcie profilowe.|Fotografia de perfil guardada.
Upload profile photo|Profilfoto hochladen|Μεταφόρτωση φωτογραφίας προφίλ|Téléverser une photo de profil|Carica foto profilo|Subir foto de perfil|Profielfoto uploaden|Prześlij zdjęcie profilowe|Carregar fotografia de perfil
Profile|Profil|Προφίλ|Profil|Profilo|Perfil|Profiel|Profil|Perfil
Orders & tracking|Bestellungen & Sendungsverfolgung|Παραγγελίες και παρακολούθηση|Commandes et suivi|Ordini e tracking|Pedidos y seguimiento|Bestellingen en tracking|Zamówienia i śledzenie|Encomendas e rastreio
Orders & delivery|Bestellungen & Lieferung|Παραγγελίες και παράδοση|Commandes et livraison|Ordini e consegna|Pedidos y entrega|Bestellingen en bezorging|Zamówienia i dostawa|Encomendas e entrega
Manage profile & addresses|Profil & Adressen verwalten|Διαχείριση προφίλ και διευθύνσεων|Gérer profil et adresses|Gestisci profilo e indirizzi|Gestionar perfil y direcciones|Profiel en adressen beheren|Zarządzaj profilem i adresami|Gerir perfil e moradas
Sign in to view your account, or try again if the connection is unavailable.|Melden Sie sich an oder versuchen Sie es bei Verbindungsproblemen erneut.|Συνδεθείτε ή δοκιμάστε ξανά αν η σύνδεση δεν είναι διαθέσιμη.|Connectez-vous ou réessayez si la connexion est indisponible.|Accedi o riprova se la connessione non è disponibile.|Inicia sesión o reintenta si la conexión no está disponible.|Log in of probeer opnieuw bij verbindingsproblemen.|Zaloguj się lub spróbuj ponownie przy problemach z połączeniem.|Inicie sessão ou tente novamente se a ligação não estiver disponível.
Shopify sends a one-time code to your email. No password is needed.|Shopify sendet einen Einmalcode per E-Mail. Kein Passwort erforderlich.|Το Shopify στέλνει κωδικό μιας χρήσης στο email σας. Δεν χρειάζεται κωδικός πρόσβασης.|Shopify envoie un code unique par e-mail. Aucun mot de passe nécessaire.|Shopify invia un codice monouso via email. Non serve una password.|Shopify envía un código de un solo uso por correo. No necesitas contraseña.|Shopify stuurt een eenmalige code per e-mail. Geen wachtwoord nodig.|Shopify wysyła jednorazowy kod e-mailem. Hasło nie jest potrzebne.|A Shopify envia um código único por email. Não precisa de palavra-passe.
Open Shopify account|Shopify-Konto öffnen|Άνοιγμα λογαριασμού Shopify|Ouvrir le compte Shopify|Apri account Shopify|Abrir cuenta Shopify|Shopify-account openen|Otwórz konto Shopify|Abrir conta Shopify
Language|Sprache|Γλώσσα|Langue|Lingua|Idioma|Taal|Język|Idioma
Choose your country|Wählen Sie Ihr Land|Επιλέξτε τη χώρα σας|Choisissez votre pays|Scegli il tuo paese|Elige tu país|Kies je land|Wybierz kraj|Escolha o seu país
ONE MALL. DIFFERENT DESTINATIONS.|EIN EINKAUFSZENTRUM. VIELE LÄNDER.|ΕΝΑ ΕΜΠΟΡΙΚΟ ΚΕΝΤΡΟ. ΠΟΛΛΟΙ ΠΡΟΟΡΙΣΜΟΙ.|UN CENTRE. PLUSIEURS DESTINATIONS.|UN CENTRO. DIVERSE DESTINAZIONI.|UN CENTRO. DISTINTOS DESTINOS.|ÉÉN CENTRUM. VERSCHILLENDE BESTEMMINGEN.|JEDNO CENTRUM. RÓŻNE KIERUNKI.|UM CENTRO. DIFERENTES DESTINOS.
Your world.|Ihre Welt.|Ο κόσμος σας.|Votre monde.|Il tuo mondo.|Tu mundo.|Jouw wereld.|Twój świat.|O seu mundo.
Your|Ihr|Το δικό σας|Votre|Il tuo|Tu|Jouw|Twój|O seu
Choose a country. Step inside its mall.|Wählen Sie ein Land. Betreten Sie sein Einkaufszentrum.|Επιλέξτε χώρα. Μπείτε στο εμπορικό της κέντρο.|Choisissez un pays. Entrez dans son centre commercial.|Scegli un paese. Entra nel suo centro commerciale.|Elige un país. Entra en su centro comercial.|Kies een land. Stap het winkelcentrum binnen.|Wybierz kraj. Wejdź do jego centrum handlowego.|Escolha um país. Entre no seu centro comercial.
Discover a collection made for your destination.|Entdecken Sie die Kollektion Ihres Landes.|Ανακαλύψτε τη συλλογή του προορισμού σας.|Découvrez la collection de votre destination.|Scopri la collezione della tua destinazione.|Descubre la colección de tu destino.|Ontdek de collectie voor jouw bestemming.|Odkryj kolekcję dla swojego kraju.|Descubra a coleção do seu destino.
Explore our country stores|Entdecken Sie unsere Länder-Shops|Εξερευνήστε τα καταστήματα ανά χώρα|Explorez nos boutiques par pays|Esplora i nostri negozi per paese|Explora nuestras tiendas por país|Ontdek onze winkels per land|Odkryj nasze sklepy według kraju|Explore as nossas lojas por país
EUROPE / SELECT YOUR DESTINATION|EUROPA / LAND WÄHLEN|ΕΥΡΩΠΗ / ΕΠΙΛΕΞΤΕ ΠΡΟΟΡΙΣΜΟ|EUROPE / CHOISISSEZ VOTRE DESTINATION|EUROPA / SCEGLI LA DESTINAZIONE|EUROPA / ELIGE TU DESTINO|EUROPA / KIES JE BESTEMMING|EUROPA / WYBIERZ KIERUNEK|EUROPA / ESCOLHA O DESTINO
Where are you shopping?|Wo möchten Sie einkaufen?|Πού θέλετε να ψωνίσετε;|Où souhaitez-vous acheter ?|Dove vuoi fare acquisti?|¿Dónde quieres comprar?|Waar wil je winkelen?|Gdzie chcesz robić zakupy?|Onde quer fazer compras?
Each destination has its own collection.|Jedes Land hat seine eigene Kollektion.|Κάθε χώρα έχει τη δική της συλλογή.|Chaque pays a sa collection.|Ogni paese ha la sua collezione.|Cada país tiene su colección.|Elk land heeft een eigen collectie.|Każdy kraj ma własną kolekcję.|Cada país tem a sua coleção.
Select your destination to explore its stores. Product availability, delivery and payment options are confirmed at checkout.|Wählen Sie ein Land, um seine Shops zu entdecken. Verfügbarkeit, Lieferung und Zahlungsoptionen werden an der Kasse bestätigt.|Επιλέξτε χώρα για να δείτε τα καταστήματα. Διαθεσιμότητα, παράδοση και τρόποι πληρωμής επιβεβαιώνονται στο ταμείο.|Choisissez un pays pour découvrir ses boutiques. Disponibilité, livraison et paiement sont confirmés à la caisse.|Scegli un paese per esplorare i negozi. Disponibilità, consegna e pagamento sono confermati alla cassa.|Elige un país para explorar sus tiendas. Disponibilidad, entrega y pago se confirman al finalizar la compra.|Kies een land om de winkels te ontdekken. Beschikbaarheid, bezorging en betaling worden bij het afrekenen bevestigd.|Wybierz kraj, aby poznać sklepy. Dostępność, dostawa i płatność są potwierdzane przy kasie.|Escolha um país para explorar as lojas. Disponibilidade, entrega e pagamento são confirmados na finalização da compra.
Explore VIZIMALL {place}|VIZIMALL {place} entdecken|Εξερευνήστε το VIZIMALL {place}|Explorez VIZIMALL {place}|Esplora VIZIMALL {place}|Explora VIZIMALL {place}|Ontdek VIZIMALL {place}|Odkryj VIZIMALL {place}|Explore VIZIMALL {place}
Map of Europe|Europakarte|Χάρτης Ευρώπης|Carte de l’Europe|Mappa d’Europa|Mapa de Europa|Kaart van Europa|Mapa Europy|Mapa da Europa
Choose a country on the map of Europe|Wählen Sie ein Land auf der Europakarte|Επιλέξτε χώρα στον χάρτη Ευρώπης|Choisissez un pays sur la carte d’Europe|Scegli un paese sulla mappa d’Europa|Elige un país en el mapa de Europa|Kies een land op de kaart van Europa|Wybierz kraj na mapie Europy|Escolha um país no mapa da Europa
You are shopping the {place} collection. Your delivery address can be in another country, but delivery may take longer or be unavailable. Shipping options, final prices and taxes are calculated in Shopify checkout. You can check out as a guest.|Sie kaufen in der Kollektion aus {place} ein. Die Lieferadresse kann in einem anderen Land liegen; Lieferung kann länger dauern oder nicht verfügbar sein. Versand, Endpreise und Steuern werden an der Shopify-Kasse berechnet. Sie können als Gast bezahlen.|Αγοράζετε από τη συλλογή {place}. Η διεύθυνση μπορεί να είναι σε άλλη χώρα, αλλά η παράδοση μπορεί να καθυστερεί ή να μην διατίθεται. Αποστολή, τελικές τιμές και φόροι υπολογίζονται στο Shopify. Μπορείτε να αγοράσετε ως επισκέπτης.|Vous achetez la collection de {place}. L’adresse peut être dans un autre pays, avec un délai supérieur ou sans livraison possible. Livraison, prix finaux et taxes sont calculés à la caisse Shopify. Le paiement invité est possible.|Acquisti dalla collezione di {place}. L’indirizzo può essere in un altro paese, ma la consegna può richiedere più tempo o non essere disponibile. Spedizione, prezzi finali e imposte sono calcolati alla cassa Shopify. Puoi acquistare come ospite.|Compras en la colección de {place}. La dirección puede estar en otro país, con entrega más lenta o no disponible. Envío, precios finales e impuestos se calculan en Shopify. Puedes comprar como invitado.|Je koopt uit de collectie van {place}. Het adres kan in een ander land liggen, maar bezorging kan langer duren of ontbreken. Verzending, eindprijzen en belastingen worden bij Shopify berekend. Je kunt als gast afrekenen.|Kupujesz z kolekcji {place}. Adres może być w innym kraju, ale dostawa może trwać dłużej lub być niedostępna. Dostawa, ceny końcowe i podatki są obliczane w kasie Shopify. Możesz kupić jako gość.|Compra na coleção de {place}. A morada pode estar noutro país, mas a entrega pode demorar mais ou não estar disponível. Envio, preços finais e impostos são calculados na Shopify. Pode comprar como convidado.
Your bag|Ihr Warenkorb|Το καλάθι σας|Votre panier|Il tuo carrello|Tu cesta|Je tas|Twój koszyk|O seu carrinho
Open bag ({count} items)|Warenkorb öffnen ({count} Artikel)|Άνοιγμα καλαθιού ({count} είδη)|Ouvrir le panier ({count} articles)|Apri carrello ({count} articoli)|Abrir cesta ({count} artículos)|Tas openen ({count} artikelen)|Otwórz koszyk ({count} sztuk)|Abrir carrinho ({count} artigos)
Mall panorama. Use left and right arrow keys to explore.|Einkaufszentrum-Panorama. Mit den Pfeiltasten links und rechts erkunden.|Πανόραμα εμπορικού κέντρου. Εξερευνήστε με τα βελάκια αριστερά και δεξιά.|Panorama du centre. Explorez avec les flèches gauche et droite.|Panorama del centro. Esplora con le frecce sinistra e destra.|Panorama del centro. Explora con las flechas izquierda y derecha.|Panorama van het centrum. Ontdek met de linker- en rechterpijl.|Panorama centrum. Odkrywaj strzałkami w lewo i w prawo.|Panorama do centro. Explore com as setas esquerda e direita.
Vizimall panoramic shopping mall interior|Panorama des Vizimall-Einkaufszentrums|Πανοραμική άποψη του Vizimall|Vue panoramique du centre Vizimall|Panorama del centro Vizimall|Panorama del centro Vizimall|Panorama van het Vizimall-centrum|Panorama centrum Vizimall|Panorama do centro Vizimall
Delivery details for this destination have not been provided. Final availability and charges are confirmed with your address at checkout.|Für dieses Lieferland wurden noch keine Lieferdetails bereitgestellt. Verfügbarkeit und Kosten werden mit Ihrer Adresse an der Kasse bestätigt.|Δεν παρέχονται λεπτομέρειες παράδοσης για αυτόν τον προορισμό. Διαθεσιμότητα και χρεώσεις επιβεβαιώνονται με τη διεύθυνσή σας στο ταμείο.|Les détails de livraison pour cette destination ne sont pas fournis. Disponibilité et frais sont confirmés avec votre adresse à la caisse.|Dettagli di consegna non forniti per questa destinazione. Disponibilità e costi sono confermati con l’indirizzo alla cassa.|No hay detalles de entrega para este destino. Disponibilidad y costes se confirman con tu dirección al pagar.|Bezorggegevens voor deze bestemming zijn niet opgegeven. Beschikbaarheid en kosten worden met je adres bij het afrekenen bevestigd.|Brak danych dostawy dla tego kierunku. Dostępność i koszty są potwierdzane dla adresu przy kasie.|Não existem detalhes de entrega para este destino. Disponibilidade e custos são confirmados com a morada na finalização da compra.
Product|Produkt|Προϊόν|Produit|Prodotto|Producto|Product|Produkt|Produto
Help|Hilfe|Βοήθεια|Aide|Assistenza|Ayuda|Hulp|Pomoc|Ajuda
Back to mall|Zurück zum Einkaufszentrum|Επιστροφή στο εμπορικό κέντρο|Retour au centre commercial|Torna al centro commerciale|Volver al centro comercial|Terug naar het winkelcentrum|Powrót do centrum handlowego|Voltar ao centro comercial
Color|Farbe|Χρώμα|Couleur|Colore|Color|Kleur|Kolor|Cor
Size|Größe|Μέγεθος|Taille|Taglia|Talla|Maat|Rozmiar|Tamanho
Model|Modell|Μοντέλο|Modèle|Modello|Modelo|Model|Model|Modelo
Standard|Standard|Τυπικό|Standard|Standard|Estándar|Standaard|Standard|Padrão
Destination check unavailable|Lieferländerprüfung nicht verfügbar|Έλεγχος προορισμών μη διαθέσιμος|Vérification des destinations indisponible|Verifica destinazioni non disponibile|Comprobación de destinos no disponible|Bestemmingscontrole niet beschikbaar|Sprawdzanie kierunków niedostępne|Verificação de destinos indisponível
{count} product|{count} Produkt|{count} προϊόν|{count} produit|{count} prodotto|{count} producto|{count} product|{count} produkt|{count} produto
Product page {index}|Produktseite {index}|Σελίδα προϊόντων {index}|Page de produits {index}|Pagina prodotti {index}|Página de productos {index}|Productpagina {index}|Strona produktów {index}|Página de produtos {index}
View {product}|{product} ansehen|Προβολή {product}|Voir {product}|Visualizza {product}|Ver {product}|Bekijk {product}|Zobacz {product}|Ver {product}
Enlarge photo of {product}|Foto von {product} vergrößern|Μεγέθυνση φωτογραφίας {product}|Agrandir la photo de {product}|Ingrandisci foto di {product}|Ampliar foto de {product}|Foto van {product} vergroten|Powiększ zdjęcie {product}|Ampliar fotografia de {product}
Show photo {index} of {count}|Foto {index} von {count} anzeigen|Εμφάνιση φωτογραφίας {index} από {count}|Afficher la photo {index} sur {count}|Mostra foto {index} di {count}|Mostrar foto {index} de {count}|Foto {index} van {count} tonen|Pokaż zdjęcie {index} z {count}|Mostrar fotografia {index} de {count}
Photos of {product}|Fotos von {product}|Φωτογραφίες {product}|Photos de {product}|Foto di {product}|Fotos de {product}|Foto’s van {product}|Zdjęcia {product}|Fotografias de {product}
Choose {option}: {value}|{option} wählen: {value}|Επιλέξτε {option}: {value}|Choisir {option} : {value}|Scegli {option}: {value}|Elegir {option}: {value}|Kies {option}: {value}|Wybierz {option}: {value}|Escolher {option}: {value}
Quantity for {product}|Menge für {product}|Ποσότητα για {product}|Quantité pour {product}|Quantità per {product}|Cantidad de {product}|Aantal voor {product}|Ilość dla {product}|Quantidade de {product}
`;
  const codes=Object.keys(root.VizimallLocaleData.languages);
  for(const line of rows.trim().split('\n')){const[key,...values]=line.split('|');if(values.length!==8)throw Error('Invalid locale row: '+key);root.VizimallLocaleData.messages[key]=Object.fromEntries(codes.map((code,i)=>[code,values[i]]));}
})(typeof window==='undefined'?globalThis:window);
