(function(root){
  'use strict';
  // Columns: DE, GR, FR, IT, ES, NL, PL, PT. UI only; never supplier content.
  const languages={DE:'de',GR:'el',FR:'fr',IT:'it',ES:'es',NL:'nl',PL:'pl',PT:'pt-PT'};
  const columns=Object.keys(languages);
  const rows=`
← Back to mall|← Zurück zum Einkaufszentrum|← Επιστροφή στο εμπορικό κέντρο|← Retour au centre commercial|← Torna al centro commerciale|← Volver al centro comercial|← Terug naar het winkelcentrum|← Powrót do centrum handlowego|← Voltar ao centro comercial
My account|Mein Konto|Ο λογαριασμός μου|Mon compte|Il mio account|Mi cuenta|Mijn account|Moje konto|A minha conta
Sign in|Anmelden|Σύνδεση|Se connecter|Accedi|Iniciar sesión|Inloggen|Zaloguj się|Iniciar sessão
Sign out|Abmelden|Αποσύνδεση|Se déconnecter|Esci|Cerrar sesión|Uitloggen|Wyloguj się|Terminar sessão
Sign in or open your profile|Anmelden oder Profil öffnen|Συνδεθείτε ή ανοίξτε το προφίλ σας|Se connecter ou ouvrir votre profil|Accedi o apri il tuo profilo|Inicia sesión o abre tu perfil|Log in of open je profiel|Zaloguj się lub otwórz profil|Inicie sessão ou abra o perfil
Collection|Kollektion|Συλλογή|Collection|Collezione|Colección|Collectie|Kolekcja|Coleção
Discover the collection|Kollektion entdecken|Ανακαλύψτε τη συλλογή|Découvrez la collection|Scopri la collezione|Descubre la colección|Ontdek de collectie|Odkryj kolekcję|Descubra a coleção
Loading the collection…|Kollektion wird geladen…|Φόρτωση συλλογής…|Chargement de la collection…|Caricamento della collezione…|Cargando la colección…|Collectie laden…|Ładowanie kolekcji…|A carregar a coleção…
Choose a product to explore its options.|Wählen Sie ein Produkt, um seine Optionen zu sehen.|Επιλέξτε ένα προϊόν για να δείτε τις επιλογές του.|Choisissez un produit pour voir ses options.|Scegli un prodotto per vedere le opzioni.|Elige un producto para ver sus opciones.|Kies een product om de opties te bekijken.|Wybierz produkt, aby zobaczyć opcje.|Escolha um produto para ver as opções.
Search this store|In diesem Shop suchen|Αναζήτηση στο κατάστημα|Rechercher dans cette boutique|Cerca in questo negozio|Buscar en esta tienda|Zoeken in deze winkel|Szukaj w tym sklepie|Pesquisar nesta loja
Sort products|Produkte sortieren|Ταξινόμηση προϊόντων|Trier les produits|Ordina prodotti|Ordenar productos|Producten sorteren|Sortuj produkty|Ordenar produtos
Name A–Z|Name A–Z|Όνομα Α–Ω|Nom A–Z|Nome A–Z|Nombre A–Z|Naam A–Z|Nazwa A–Z|Nome A–Z
Price: low to high|Preis: aufsteigend|Τιμή: αύξουσα|Prix : croissant|Prezzo: crescente|Precio: menor a mayor|Prijs: laag naar hoog|Cena: rosnąco|Preço: crescente
Price: high to low|Preis: absteigend|Τιμή: φθίνουσα|Prix : décroissant|Prezzo: decrescente|Precio: mayor a menor|Prijs: hoog naar laag|Cena: malejąco|Preço: decrescente
In stock only|Nur verfügbare Produkte|Μόνο διαθέσιμα|En stock uniquement|Solo disponibili|Solo disponibles|Alleen op voorraad|Tylko dostępne|Apenas em stock
Minimum price|Mindestpreis|Ελάχιστη τιμή|Prix minimum|Prezzo minimo|Precio mínimo|Minimumprijs|Cena minimalna|Preço mínimo
Maximum price|Höchstpreis|Μέγιστη τιμή|Prix maximum|Prezzo massimo|Precio máximo|Maximumprijs|Cena maksymalna|Preço máximo
Min price|Min. Preis|Ελάχ. τιμή|Prix min.|Prezzo min.|Precio mín.|Min. prijs|Cena min.|Preço mín.
Max price|Max. Preis|Μέγ. τιμή|Prix max.|Prezzo max.|Precio máx.|Max. prijs|Cena maks.|Preço máx.
Choose options|Optionen wählen|Επιλογή παραλλαγής|Choisir les options|Scegli le opzioni|Elegir opciones|Opties kiezen|Wybierz opcje|Escolher opções
♡ Save favourite|♡ Merken|♡ Αποθήκευση αγαπημένου|♡ Ajouter aux favoris|♡ Salva nei preferiti|♡ Guardar favorito|♡ Bewaar favoriet|♡ Dodaj do ulubionych|♡ Guardar favorito
♥ Saved|♥ Gespeichert|♥ Αποθηκεύτηκε|♥ Enregistré|♥ Salvato|♥ Guardado|♥ Opgeslagen|♥ Zapisano|♥ Guardado
Close|Schließen|Κλείσιμο|Fermer|Chiudi|Cerrar|Sluiten|Zamknij|Fechar
Loading product options…|Produktoptionen werden geladen…|Φόρτωση επιλογών προϊόντος…|Chargement des options…|Caricamento delle opzioni…|Cargando las opciones…|Productopties laden…|Ładowanie opcji produktu…|A carregar as opções…
Product details|Produktdetails|Λεπτομέρειες προϊόντος|Détails du produit|Dettagli prodotto|Detalles del producto|Productgegevens|Szczegóły produktu|Detalhes do produto
Delivery|Lieferung|Παράδοση|Livraison|Consegna|Entrega|Levering|Dostawa|Entrega
Delivery information|Lieferinformationen|Πληροφορίες παράδοσης|Informations de livraison|Informazioni di consegna|Información de entrega|Leveringsinformatie|Informacje o dostawie|Informações de entrega
Ship to:|Liefern nach:|Αποστολή προς:|Livrer en :|Spedisci a:|Enviar a:|Verzenden naar:|Wysyłka do:|Enviar para:
Product shipping country|Lieferland des Produkts|Χώρα παράδοσης προϊόντος|Pays de livraison du produit|Paese di consegna del prodotto|País de entrega del producto|Bezorgland van het product|Kraj dostawy produktu|País de entrega do produto
Choose delivery country|Lieferland wählen|Επιλέξτε χώρα παράδοσης|Choisir le pays de livraison|Scegli il paese di consegna|Elegir país de entrega|Kies bezorgland|Wybierz kraj dostawy|Escolher país de entrega
Checking available delivery countries…|Verfügbare Lieferländer werden geprüft…|Έλεγχος διαθέσιμων χωρών παράδοσης…|Vérification des pays de livraison…|Verifica dei paesi di consegna…|Comprobando países de entrega…|Beschikbare bezorglanden controleren…|Sprawdzanie krajów dostawy…|A verificar os países de entrega…
Only destinations confirmed by CJ are listed.|Es werden nur von CJ bestätigte Lieferländer angezeigt.|Εμφανίζονται μόνο χώρες που επιβεβαίωσε η CJ.|Seules les destinations confirmées par CJ sont affichées.|Sono mostrate solo le destinazioni confermate da CJ.|Solo se muestran destinos confirmados por CJ.|Alleen door CJ bevestigde bestemmingen worden getoond.|Wyświetlane są tylko kierunki potwierdzone przez CJ.|São apresentados apenas destinos confirmados pela CJ.
Some country checks could not be completed.|Einige Länderprüfungen konnten nicht abgeschlossen werden.|Ορισμένοι έλεγχοι χωρών δεν ολοκληρώθηκαν.|Certaines vérifications de pays n’ont pas abouti.|Alcune verifiche dei paesi non sono state completate.|No se pudieron completar algunas comprobaciones.|Sommige landen konden niet worden gecontroleerd.|Nie udało się sprawdzić niektórych krajów.|Não foi possível concluir algumas verificações.
CJ has no confirmed delivery destinations for this option.|CJ hat für diese Option keine Lieferländer bestätigt.|Η CJ δεν έχει επιβεβαιώσει χώρες παράδοσης για αυτή την επιλογή.|CJ n’a confirmé aucune destination pour cette option.|CJ non ha confermato destinazioni per questa opzione.|CJ no ha confirmado destinos para esta opción.|CJ heeft voor deze optie geen bestemmingen bevestigd.|CJ nie potwierdziło kierunków dostawy dla tej opcji.|A CJ não confirmou destinos para esta opção.
Delivery countries could not be confirmed for this option.|Lieferländer konnten für diese Option nicht bestätigt werden.|Δεν επιβεβαιώθηκαν χώρες παράδοσης για αυτή την επιλογή.|Les pays de livraison n’ont pas pu être confirmés pour cette option.|Impossibile confermare i paesi di consegna per questa opzione.|No se pudieron confirmar países de entrega para esta opción.|Bezorglanden konden voor deze optie niet worden bevestigd.|Nie udało się potwierdzić krajów dostawy dla tej opcji.|Não foi possível confirmar países de entrega para esta opção.
Only confirmed countries are shown. Checking additional destinations…|Nur bestätigte Länder werden angezeigt. Weitere Lieferländer werden geprüft…|Εμφανίζονται μόνο επιβεβαιωμένες χώρες. Έλεγχος επιπλέον προορισμών…|Seuls les pays confirmés sont affichés. Vérification d’autres destinations…|Sono mostrati solo i paesi confermati. Verifica di altre destinazioni…|Solo se muestran países confirmados. Comprobando más destinos…|Alleen bevestigde landen worden getoond. Meer bestemmingen controleren…|Wyświetlane są tylko potwierdzone kraje. Sprawdzanie kolejnych kierunków…|São apresentados apenas países confirmados. A verificar mais destinos…
Quantity|Menge|Ποσότητα|Quantité|Quantità|Cantidad|Aantal|Ilość|Quantidade
Quantity:|Menge:|Ποσότητα:|Quantité :|Quantità:|Cantidad:|Aantal:|Ilość:|Quantidade:
Shipping quote quantity|Menge für Versandberechnung|Ποσότητα για υπολογισμό μεταφορικών|Quantité pour le calcul des frais|Quantità per il calcolo della spedizione|Cantidad para calcular el envío|Aantal voor verzendberekening|Ilość do obliczenia dostawy|Quantidade para cálculo do envio
Shipping from:|Versand aus:|Αποστολή από:|Expédié depuis :|Spedizione da:|Envío desde:|Verzending vanuit:|Wysyłka z:|Envio de:
Shipping origin|Versandlager|Αποθήκη αποστολής|Entrepôt d’expédition|Magazzino di origine|Almacén de origen|Verzendmagazijn|Magazyn wysyłki|Armazém de origem
Shipping method|Versandart|Τρόπος αποστολής|Mode de livraison|Metodo di spedizione|Método de envío|Verzendmethode|Sposób dostawy|Método de envio
Shipping method:|Versandart:|Τρόπος αποστολής:|Mode de livraison :|Metodo di spedizione:|Método de envío:|Verzendmethode:|Sposób dostawy:|Método de envio:
Standard shipping:|Standardversand:|Κανονική αποστολή:|Livraison standard :|Spedizione standard:|Envío estándar:|Standaardverzending:|Dostawa standardowa:|Envio normal:
Processing time|Vorbereitungszeit|Χρόνος προετοιμασίας|Temps de préparation|Tempo di preparazione|Tiempo de preparación|Verwerkingstijd|Czas przygotowania|Tempo de preparação
Estimated delivery|Geschätzte Lieferung|Εκτιμώμενη παράδοση|Livraison estimée|Consegna stimata|Entrega estimada|Geschatte levering|Szacowana dostawa|Entrega estimada
Estimated transport|Geschätzte Transportzeit|Εκτιμώμενος χρόνος μεταφοράς|Transport estimé|Trasporto stimato|Transporte estimado|Geschatte transporttijd|Szacowany czas transportu|Transporte estimado
Warehouse stock|Lagerbestand|Απόθεμα αποθήκης|Stock de l’entrepôt|Scorte di magazzino|Stock del almacén|Magazijnvoorraad|Stan magazynowy|Stock do armazém
CJ shipping estimate for this quantity|CJ-Versandkosten für diese Menge|Εκτίμηση μεταφορικών CJ για αυτή την ποσότητα|Frais CJ estimés pour cette quantité|Spedizione CJ stimata per questa quantità|Envío CJ estimado para esta cantidad|CJ-verzendkosten voor dit aantal|Szacowane koszty CJ dla tej ilości|Estimativa de envio CJ para esta quantidade
Price including standard shipping per item|Stückpreis inklusive Standardversand|Τιμή ανά τεμάχιο με κανονική αποστολή|Prix unitaire avec livraison standard|Prezzo unitario con spedizione standard|Precio unitario con envío estándar|Prijs per artikel inclusief standaardverzending|Cena za sztukę z dostawą standardową|Preço unitário com envio normal
Shipping cost|Versandkosten|Μεταφορικά|Frais de livraison|Costo di spedizione|Gastos de envío|Verzendkosten|Koszt dostawy|Custos de envio
Confirmed at checkout|Bei der Zahlung bestätigt|Επιβεβαίωση στο ταμείο|Confirmé au paiement|Confermato al pagamento|Confirmado al pagar|Bevestigd bij het afrekenen|Potwierdzone przy płatności|Confirmado no pagamento
Not provided|Nicht angegeben|Δεν παρέχεται|Non indiqué|Non indicato|No indicado|Niet opgegeven|Nie podano|Não indicado
Not provided by supplier|Vom Lieferanten nicht angegeben|Δεν παρέχεται από τον προμηθευτή|Non indiqué par le fournisseur|Non indicato dal fornitore|No indicado por el proveedor|Niet opgegeven door de leverancier|Nie podano przez dostawcę|Não indicado pelo fornecedor
Not provided for this destination|Für dieses Lieferland nicht angegeben|Δεν παρέχεται για αυτόν τον προορισμό|Non indiqué pour cette destination|Non indicato per questa destinazione|No indicado para este destino|Niet opgegeven voor deze bestemming|Nie podano dla tego kierunku|Não indicado para este destino
Availability|Verfügbarkeit|Διαθεσιμότητα|Disponibilité|Disponibilità|Disponibilidad|Beschikbaarheid|Dostępność|Disponibilidade
No shipping option available for this quantity and destination.|Für diese Menge und dieses Lieferland ist kein Versand verfügbar.|Δεν υπάρχει αποστολή για αυτή την ποσότητα και τον προορισμό.|Aucune livraison disponible pour cette quantité et cette destination.|Nessuna spedizione disponibile per questa quantità e destinazione.|No hay envío disponible para esta cantidad y destino.|Geen verzending beschikbaar voor dit aantal en deze bestemming.|Brak dostawy dla tej ilości i kierunku.|Não existe envio para esta quantidade e destino.
Choose another destination or quantity.|Wählen Sie ein anderes Lieferland oder eine andere Menge.|Επιλέξτε άλλον προορισμό ή ποσότητα.|Choisissez une autre destination ou quantité.|Scegli un’altra destinazione o quantità.|Elige otro destino o cantidad.|Kies een andere bestemming of een ander aantal.|Wybierz inny kierunek lub ilość.|Escolha outro destino ou quantidade.
Standard shipping is included per item.|Standardversand ist pro Stück enthalten.|Η κανονική αποστολή περιλαμβάνεται ανά τεμάχιο.|La livraison standard est incluse par article.|La spedizione standard è inclusa per articolo.|El envío estándar está incluido por artículo.|Standaardverzending is inbegrepen per artikel.|Dostawa standardowa jest wliczona za sztukę.|O envio normal está incluído por artigo.
Shipping is available. The checkout price for this destination is being prepared; purchasing is temporarily unavailable.|Versand verfügbar. Der Preis für dieses Lieferland wird vorbereitet; der Kauf ist vorübergehend nicht möglich.|Η αποστολή είναι διαθέσιμη. Προετοιμάζεται η τιμή για αυτόν τον προορισμό· η αγορά προσωρινά δεν είναι διαθέσιμη.|Livraison disponible. Le prix pour cette destination est en préparation ; l’achat est temporairement indisponible.|Spedizione disponibile. Il prezzo per questa destinazione è in preparazione; l’acquisto è temporaneamente non disponibile.|Envío disponible. Se está preparando el precio para este destino; la compra no está disponible temporalmente.|Verzending beschikbaar. De prijs voor deze bestemming wordt voorbereid; kopen is tijdelijk niet mogelijk.|Dostawa dostępna. Cena dla tego kierunku jest przygotowywana; zakup jest chwilowo niedostępny.|Envio disponível. O preço para este destino está a ser preparado; a compra está temporariamente indisponível.
Preparation and transport are separate estimates.|Vorbereitung und Transport sind getrennte Schätzungen.|Η προετοιμασία και η μεταφορά είναι ξεχωριστές εκτιμήσεις.|Préparation et transport sont des estimations distinctes.|Preparazione e trasporto sono stime separate.|Preparación y transporte son estimaciones independientes.|Voorbereiding en transport zijn afzonderlijke schattingen.|Przygotowanie i transport to oddzielne szacunki.|A preparação e o transporte são estimativas separadas.
Sold out|Ausverkauft|Εξαντλήθηκε|Épuisé|Esaurito|Agotado|Uitverkocht|Wyprzedane|Esgotado
Add to bag|In den Warenkorb|Προσθήκη στο καλάθι|Ajouter au panier|Aggiungi al carrello|Añadir al carrito|In winkelmand|Dodaj do koszyka|Adicionar ao carrinho
View bag|Warenkorb ansehen|Προβολή καλαθιού|Voir le panier|Vedi carrello|Ver carrito|Winkelmand bekijken|Zobacz koszyk|Ver carrinho
Checking shipping…|Versand wird geprüft…|Έλεγχος αποστολής…|Vérification de la livraison…|Verifica della spedizione…|Comprobando envío…|Verzending controleren…|Sprawdzanie dostawy…|A verificar o envio…
Checking destination price…|Preis für Lieferland wird geprüft…|Έλεγχος τιμής προορισμού…|Vérification du prix de destination…|Verifica del prezzo di destinazione…|Comprobando precio de destino…|Bestemmingsprijs controleren…|Sprawdzanie ceny dla kierunku…|A verificar o preço do destino…
Checkout price pending|Preis wird vorbereitet|Η τιμή προετοιμάζεται|Prix en préparation|Prezzo in preparazione|Precio pendiente|Prijs wordt voorbereid|Cena w przygotowaniu|Preço em preparação
Shipping unavailable|Versand nicht verfügbar|Η αποστολή δεν είναι διαθέσιμη|Livraison indisponible|Spedizione non disponibile|Envío no disponible|Verzending niet beschikbaar|Dostawa niedostępna|Envio indisponível
Added to your bag.|Zum Warenkorb hinzugefügt.|Προστέθηκε στο καλάθι.|Ajouté au panier.|Aggiunto al carrello.|Añadido al carrito.|Toegevoegd aan je winkelmand.|Dodano do koszyka.|Adicionado ao carrinho.
Remove|Entfernen|Αφαίρεση|Retirer|Rimuovi|Eliminar|Verwijderen|Usuń|Remover
Secure checkout|Sicher bezahlen|Ασφαλής πληρωμή|Paiement sécurisé|Pagamento sicuro|Pago seguro|Veilig afrekenen|Bezpieczna płatność|Pagamento seguro
Your bag is empty. Explore the stores to find something you love.|Ihr Warenkorb ist leer. Entdecken Sie unsere Shops.|Το καλάθι είναι άδειο. Ανακαλύψτε τα καταστήματά μας.|Votre panier est vide. Découvrez nos boutiques.|Il carrello è vuoto. Esplora i nostri negozi.|Tu carrito está vacío. Explora nuestras tiendas.|Je winkelmand is leeg. Ontdek onze winkels.|Koszyk jest pusty. Odkryj nasze sklepy.|O carrinho está vazio. Explore as nossas lojas.
Customer reviews|Kundenbewertungen|Αξιολογήσεις πελατών|Avis clients|Recensioni dei clienti|Reseñas de clientes|Klantbeoordelingen|Opinie klientów|Avaliações de clientes
No customer reviews yet.|Noch keine Kundenbewertungen.|Δεν υπάρχουν ακόμη αξιολογήσεις.|Aucun avis client pour le moment.|Ancora nessuna recensione.|Todavía no hay reseñas.|Nog geen klantbeoordelingen.|Brak opinii klientów.|Ainda não existem avaliações.
No reviews yet|Noch keine Bewertungen|Χωρίς αξιολογήσεις ακόμη|Aucun avis pour le moment|Ancora nessuna recensione|Sin reseñas todavía|Nog geen beoordelingen|Brak opinii|Ainda sem avaliações
Help & returns|Hilfe & Rückgaben|Βοήθεια και επιστροφές|Aide et retours|Assistenza e resi|Ayuda y devoluciones|Hulp en retouren|Pomoc i zwroty|Ajuda e devoluções
Privacy & cookies|Datenschutz & Cookies|Απόρρητο και cookies|Confidentialité et cookies|Privacy e cookie|Privacidad y cookies|Privacy en cookies|Prywatność i pliki cookie|Privacidade e cookies
Email updates|Neuigkeiten per E-Mail|Ενημερώσεις μέσω email|Actualités par e-mail|Novità via email|Novedades por correo|Updates per e-mail|Aktualności e-mail|Novidades por email
Cookie preferences|Cookie-Einstellungen|Προτιμήσεις cookies|Préférences des cookies|Preferenze cookie|Preferencias de cookies|Cookievoorkeuren|Ustawienia plików cookie|Preferências de cookies
Your privacy choices|Ihre Datenschutzeinstellungen|Οι επιλογές απορρήτου σας|Vos choix de confidentialité|Le tue scelte di privacy|Tus opciones de privacidad|Je privacykeuzes|Twoje ustawienia prywatności|As suas opções de privacidade
Read privacy & cookie information|Datenschutz- und Cookie-Informationen lesen|Διαβάστε τις πληροφορίες απορρήτου και cookies|Lire les informations de confidentialité et cookies|Leggi le informazioni su privacy e cookie|Leer información de privacidad y cookies|Lees informatie over privacy en cookies|Przeczytaj informacje o prywatności i plikach cookie|Ler informações de privacidade e cookies
Allow visit measurement (optional)|Besuchsmessung erlauben (optional)|Να επιτρέπεται η μέτρηση επισκέψεων (προαιρετικά)|Autoriser la mesure des visites (facultatif)|Consenti la misurazione delle visite (facoltativo)|Permitir medición de visitas (opcional)|Bezoekmeting toestaan (optioneel)|Zezwól na pomiar wizyt (opcjonalnie)|Permitir medição de visitas (opcional)
Accept optional measurement|Optionale Messung akzeptieren|Αποδοχή προαιρετικής μέτρησης|Accepter la mesure facultative|Accetta misurazione facoltativa|Aceptar medición opcional|Optionele meting accepteren|Akceptuj opcjonalny pomiar|Aceitar medição opcional
Reject optional measurement|Optionale Messung ablehnen|Απόρριψη προαιρετικής μέτρησης|Refuser la mesure facultative|Rifiuta misurazione facoltativa|Rechazar medición opcional|Optionele meting weigeren|Odrzuć opcjonalny pomiar|Rejeitar medição opcional
Manage preferences|Einstellungen verwalten|Διαχείριση προτιμήσεων|Gérer les préférences|Gestisci preferenze|Gestionar preferencias|Voorkeuren beheren|Zarządzaj ustawieniami|Gerir preferências
Save preferences|Einstellungen speichern|Αποθήκευση προτιμήσεων|Enregistrer les préférences|Salva preferenze|Guardar preferencias|Voorkeuren opslaan|Zapisz ustawienia|Guardar preferências
TECH & GADGETS|TECHNIK & GADGETS|ΤΕΧΝΟΛΟΓΙΑ & GADGETS|TECHNOLOGIE & GADGETS|TECNOLOGIA & GADGET|TECNOLOGÍA & GADGETS|TECHNIEK & GADGETS|TECHNOLOGIA & GADŻETY|TECNOLOGIA & GADGETS
HOME & LIVING|WOHNEN & HAUSHALT|ΣΠΙΤΙ & ΔΙΑΚΟΣΜΗΣΗ|MAISON & DÉCO|CASA & ARREDAMENTO|HOGAR & DECORACIÓN|HUIS & WONEN|DOM & WNĘTRZA|CASA & DECORAÇÃO
FASHION & STYLE|MODE & STIL|ΜΟΔΑ & ΣΤΥΛ|MODE & STYLE|MODA & STILE|MODA & ESTILO|MODE & STIJL|MODA & STYL|MODA & ESTILO
BEAUTY & CARE|BEAUTY & PFLEGE|ΟΜΟΡΦΙΑ & ΠΕΡΙΠΟΙΗΣΗ|BEAUTÉ & SOINS|BELLEZZA & CURA|BELLEZA & CUIDADO|BEAUTY & VERZORGING|URODA & PIELĘGNACJA|BELEZA & CUIDADOS
PETS & FRIENDS|HAUSTIERE & FREUNDE|ΚΑΤΟΙΚΙΔΙΑ & ΦΙΛΟΙ|ANIMAUX & COMPAGNONS|ANIMALI & AMICI|MASCOTAS & AMIGOS|HUISDIEREN & VRIENDEN|ZWIERZĘTA & PRZYJACIELE|ANIMAIS & AMIGOS
KIDS & PLAY|KINDER & SPIEL|ΠΑΙΔΙΑ & ΠΑΙΧΝΙΔΙ|ENFANTS & JEUX|BAMBINI & GIOCHI|NIÑOS & JUEGOS|KINDEREN & SPELEN|DZIECI & ZABAWA|CRIANÇAS & BRINCADEIRAS
AUTO & ACCESSORIES|AUTO & ZUBEHÖR|ΑΥΤΟΚΙΝΗΤΟ & ΑΞΕΣΟΥΑΡ|AUTO & ACCESSOIRES|AUTO & ACCESSORI|AUTO & ACCESORIOS|AUTO & ACCESSOIRES|AUTO & AKCESORIA|AUTO & ACESSÓRIOS
Make everyday life easier.|Den Alltag einfacher machen.|Κάντε την καθημερινότητα πιο εύκολη.|Simplifiez votre quotidien.|Semplifica la vita quotidiana.|Haz más fácil tu día a día.|Maak het dagelijks leven makkelijker.|Ułatw sobie codzienne życie.|Simplifique o dia a dia.
Useful technology for work, play and staying connected.|Nützliche Technik für Arbeit, Freizeit und Kommunikation.|Χρήσιμη τεχνολογία για εργασία, ψυχαγωγία και επικοινωνία.|Une technologie utile pour travailler, se divertir et rester connecté.|Tecnologia utile per lavorare, divertirsi e restare connessi.|Tecnología útil para trabajar, divertirse y mantenerse conectado.|Handige technologie voor werk, plezier en contact.|Przydatna technologia do pracy, rozrywki i kontaktu.|Tecnologia útil para trabalhar, divertir-se e manter o contacto.
Make yourself at home.|Fühlen Sie sich zu Hause.|Νιώστε σαν στο σπίτι σας.|Faites comme chez vous.|Sentiti a casa.|Siéntete como en casa.|Voel je thuis.|Poczuj się jak w domu.|Sinta-se em casa.
Comfort, organisation and little details for your space.|Komfort, Ordnung und kleine Details für Ihr Zuhause.|Άνεση, οργάνωση και μικρές λεπτομέρειες για τον χώρο σας.|Confort, rangement et petits détails pour votre intérieur.|Comfort, ordine e piccoli dettagli per i tuoi spazi.|Comodidad, organización y pequeños detalles para tu hogar.|Comfort, orde en kleine details voor je huis.|Komfort, porządek i drobne detale do domu.|Conforto, organização e pequenos detalhes para a sua casa.
Find your everyday style.|Finden Sie Ihren Alltagsstil.|Βρείτε το καθημερινό σας στυλ.|Trouvez votre style au quotidien.|Trova il tuo stile quotidiano.|Encuentra tu estilo diario.|Vind je dagelijkse stijl.|Znajdź swój codzienny styl.|Encontre o seu estilo diário.
Discover clothing and accessories for every day.|Entdecken Sie Kleidung und Accessoires für jeden Tag.|Ανακαλύψτε ρούχα και αξεσουάρ για κάθε μέρα.|Découvrez des vêtements et accessoires pour tous les jours.|Scopri abbigliamento e accessori per ogni giorno.|Descubre ropa y accesorios para cada día.|Ontdek kleding en accessoires voor elke dag.|Odkryj ubrania i akcesoria na co dzień.|Descubra roupa e acessórios para todos os dias.
Your everyday care ritual.|Ihr tägliches Pflegeritual.|Η καθημερινή σας περιποίηση.|Votre rituel de soin quotidien.|Il tuo rituale di cura quotidiano.|Tu ritual de cuidado diario.|Je dagelijkse verzorgingsritueel.|Twój codzienny rytuał pielęgnacji.|O seu ritual de cuidado diário.
Discover essentials for your skin, hair and daily routine.|Entdecken Sie Produkte für Haut, Haare und tägliche Pflege.|Ανακαλύψτε προϊόντα για δέρμα, μαλλιά και καθημερινή φροντίδα.|Découvrez l’essentiel pour la peau, les cheveux et les soins quotidiens.|Scopri l’essenziale per pelle, capelli e cura quotidiana.|Descubre productos para la piel, el cabello y el cuidado diario.|Ontdek producten voor huid, haar en dagelijkse verzorging.|Odkryj produkty do skóry, włosów i codziennej pielęgnacji.|Descubra produtos para pele, cabelo e cuidados diários.
For their happiest days.|Für ihre glücklichsten Tage.|Για τις πιο χαρούμενες μέρες τους.|Pour leurs plus beaux jours.|Per i loro giorni più felici.|Para sus días más felices.|Voor hun gelukkigste dagen.|Dla ich najszczęśliwszych dni.|Para os seus dias mais felizes.
Everyday care, comfort and play for your companions.|Tägliche Pflege, Komfort und Spiel für Ihre Lieblinge.|Καθημερινή φροντίδα, άνεση και παιχνίδι για τα κατοικίδιά σας.|Soins, confort et jeux au quotidien pour vos compagnons.|Cura, comfort e gioco quotidiani per i tuoi amici.|Cuidado, comodidad y juego para tus compañeros.|Dagelijkse verzorging, comfort en spel voor je huisdieren.|Codzienna opieka, wygoda i zabawa dla pupili.|Cuidados, conforto e brincadeira para os seus companheiros.
Little discoveries. Big adventures.|Kleine Entdeckungen. Große Abenteuer.|Μικρές ανακαλύψεις. Μεγάλες περιπέτειες.|Petites découvertes. Grandes aventures.|Piccole scoperte. Grandi avventure.|Pequeños descubrimientos. Grandes aventuras.|Kleine ontdekkingen. Grote avonturen.|Małe odkrycia. Wielkie przygody.|Pequenas descobertas. Grandes aventuras.
Books, toys and thoughtful finds for growing minds.|Bücher, Spielzeug und schöne Ideen für kleine Entdecker.|Βιβλία, παιχνίδια και ιδέες για παιδιά που μεγαλώνουν.|Livres, jouets et belles idées pour les esprits qui grandissent.|Libri, giochi e idee per menti in crescita.|Libros, juguetes e ideas para mentes en crecimiento.|Boeken, speelgoed en mooie vondsten voor groeiende geesten.|Książki, zabawki i pomysły dla rozwijających się dzieci.|Livros, brinquedos e ideias para mentes em crescimento.
Car care, made simple.|Autopflege leicht gemacht.|Φροντίδα αυτοκινήτου, απλά.|L’entretien auto en toute simplicité.|Cura dell’auto, semplice.|Cuidado del coche, fácil.|Autoverzorging, eenvoudig.|Pielęgnacja auta bez komplikacji.|Cuidar do carro, de forma simples.
Practical accessories for your car and everyday journeys.|Praktisches Zubehör für Ihr Auto und tägliche Fahrten.|Πρακτικά αξεσουάρ για το αυτοκίνητο και τις καθημερινές διαδρομές.|Accessoires pratiques pour votre voiture et vos trajets quotidiens.|Accessori pratici per l’auto e gli spostamenti quotidiani.|Accesorios prácticos para tu coche y tus viajes diarios.|Praktische accessoires voor je auto en dagelijkse ritten.|Praktyczne akcesoria do auta i codziennych podróży.|Acessórios práticos para o carro e deslocações diárias.
Explore VIZIMALL|VIZIMALL entdecken|Εξερευνήστε το VIZIMALL|Explorez VIZIMALL|Esplora VIZIMALL|Explora VIZIMALL|Ontdek VIZIMALL|Odkryj VIZIMALL|Explore o VIZIMALL
Drag / Swipe to explore|Zum Entdecken ziehen / wischen|Σύρετε για εξερεύνηση|Faites glisser pour explorer|Trascina / scorri per esplorare|Arrastra / desliza para explorar|Sleep / veeg om te ontdekken|Przeciągnij / przesuń, aby odkrywać|Arraste / deslize para explorar
Your profile|Ihr Profil|Το προφίλ σας|Votre profil|Il tuo profilo|Tu perfil|Je profiel|Twój profil|O seu perfil
YOUR VIZIMALL|IHR VIZIMALL|ΤΟ VIZIMALL ΣΑΣ|VOTRE VIZIMALL|IL TUO VIZIMALL|TU VIZIMALL|JOUW VIZIMALL|TWÓJ VIZIMALL|O SEU VIZIMALL
Your place at VIZIMALL.|Ihr Platz bei VIZIMALL.|Ο χώρος σας στο VIZIMALL.|Votre espace chez VIZIMALL.|Il tuo spazio su VIZIMALL.|Tu espacio en VIZIMALL.|Jouw plek bij VIZIMALL.|Twoje miejsce w VIZIMALL.|O seu espaço no VIZIMALL.
Orders, delivery updates, your favourites and reviews.|Bestellungen, Lieferupdates, Favoriten und Bewertungen.|Παραγγελίες, ενημερώσεις παράδοσης, αγαπημένα και αξιολογήσεις.|Commandes, suivi des livraisons, favoris et avis.|Ordini, aggiornamenti, preferiti e recensioni.|Pedidos, seguimiento, favoritos y reseñas.|Bestellingen, bezorgupdates, favorieten en beoordelingen.|Zamówienia, dostawy, ulubione i opinie.|Encomendas, atualizações, favoritos e avaliações.
Opening your account…|Ihr Konto wird geöffnet…|Άνοιγμα λογαριασμού…|Ouverture de votre compte…|Apertura del tuo account…|Abriendo tu cuenta…|Je account openen…|Otwieranie konta…|A abrir a sua conta…
First name|Vorname|Όνομα|Prénom|Nome|Nombre|Voornaam|Imię|Nome
Last name|Nachname|Επώνυμο|Nom|Cognome|Apellidos|Achternaam|Nazwisko|Apelido
Save name|Namen speichern|Αποθήκευση ονόματος|Enregistrer le nom|Salva nome|Guardar nombre|Naam opslaan|Zapisz imię i nazwisko|Guardar nome
Choose your look|Wählen Sie Ihr Profilbild|Επιλέξτε εμφάνιση|Choisissez votre apparence|Scegli il tuo aspetto|Elige tu imagen|Kies je uiterlijk|Wybierz swój wygląd|Escolha a sua imagem
Upload your own photo|Eigenes Foto hochladen|Ανεβάστε τη φωτογραφία σας|Importer votre photo|Carica la tua foto|Subir tu foto|Upload je eigen foto|Prześlij własne zdjęcie|Carregar a sua fotografia
Manage delivery addresses|Lieferadressen verwalten|Διαχείριση διευθύνσεων παράδοσης|Gérer les adresses de livraison|Gestisci indirizzi di consegna|Gestionar direcciones de entrega|Bezorgadressen beheren|Zarządzaj adresami dostawy|Gerir moradas de entrega
Orders|Bestellungen|Παραγγελίες|Commandes|Ordini|Pedidos|Bestellingen|Zamówienia|Encomendas
Favourites|Favoriten|Αγαπημένα|Favoris|Preferiti|Favoritos|Favorieten|Ulubione|Favoritos
Reviews|Bewertungen|Αξιολογήσεις|Avis|Recensioni|Reseñas|Beoordelingen|Opinie|Avaliações
Support|Hilfe|Υποστήριξη|Assistance|Assistenza|Asistencia|Ondersteuning|Pomoc|Apoio
Save|Speichern|Αποθήκευση|Enregistrer|Salva|Guardar|Opslaan|Zapisz|Guardar
Cancel|Abbrechen|Ακύρωση|Annuler|Annulla|Cancelar|Annuleren|Anuluj|Cancelar
Please sign in.|Bitte melden Sie sich an.|Παρακαλώ συνδεθείτε.|Veuillez vous connecter.|Accedi per continuare.|Inicia sesión.|Log in om door te gaan.|Zaloguj się.|Inicie sessão.
Loading…|Wird geladen…|Φόρτωση…|Chargement…|Caricamento…|Cargando…|Laden…|Ładowanie…|A carregar…
Retry|Erneut versuchen|Δοκιμάστε ξανά|Réessayer|Riprova|Reintentar|Opnieuw proberen|Spróbuj ponownie|Tentar novamente
Load more|Mehr laden|Περισσότερα|Afficher plus|Carica altro|Cargar más|Meer laden|Załaduj więcej|Carregar mais
Previous photo|Vorheriges Foto|Προηγούμενη φωτογραφία|Photo précédente|Foto precedente|Foto anterior|Vorige foto|Poprzednie zdjęcie|Fotografia anterior
Next photo|Nächstes Foto|Επόμενη φωτογραφία|Photo suivante|Foto successiva|Foto siguiente|Volgende foto|Następne zdjęcie|Fotografia seguinte
Choose a product photo|Produktfoto wählen|Επιλέξτε φωτογραφία προϊόντος|Choisir une photo du produit|Scegli una foto del prodotto|Elegir foto del producto|Kies een productfoto|Wybierz zdjęcie produktu|Escolher fotografia do produto
Photos are currently unavailable.|Fotos sind derzeit nicht verfügbar.|Οι φωτογραφίες δεν είναι διαθέσιμες.|Les photos sont actuellement indisponibles.|Le foto non sono disponibili.|Las fotos no están disponibles.|Foto’s zijn momenteel niet beschikbaar.|Zdjęcia są chwilowo niedostępne.|As fotografias estão indisponíveis.
Purchased this product? Write a review from your orders.|Produkt gekauft? Bewerten Sie es über Ihre Bestellungen.|Αγοράσατε αυτό το προϊόν; Αξιολογήστε το από τις παραγγελίες σας.|Produit acheté ? Donnez votre avis depuis vos commandes.|Hai acquistato questo prodotto? Scrivi una recensione dai tuoi ordini.|¿Compraste este producto? Escribe una reseña desde tus pedidos.|Dit product gekocht? Schrijf een beoordeling via je bestellingen.|Kupiono ten produkt? Dodaj opinię w swoich zamówieniach.|Comprou este produto? Avalie-o nas suas encomendas.
`;
  const messages={};
  for(const line of rows.trim().split('\n')){const [key,...values]=line.split('|');if(values.length!==8)throw Error('Invalid locale row: '+key);messages[key]=Object.fromEntries(columns.map((code,i)=>[code,values[i]]));}
  root.VizimallLocaleData=Object.freeze({languages,messages});
})(typeof window==='undefined'?globalThis:window);
