(() => {
  'use strict';
  const root=document.querySelector('#newsletter-content'); const fragment=new URLSearchParams(location.hash.slice(1)); const token=fragment.get('unsubscribe');
  const clean=new URL(location.href);for(const key of ['code','state','_y','analytics_trace_id'])clean.searchParams.delete(key);
  if(token)clean.hash='';if(clean.href!==location.href)history.replaceState(null,'',clean.href); // Never leave tokens or login codes in links/history.
  const make=(tag,text)=>{const item=document.createElement(tag);if(text)item.textContent=text;return item;};
  const button=(text)=>{const item=make('button',text);item.className='account-button';item.type='button';return item;};
  async function request(path,input){const result=await fetch('/api/'+path,{cache:'no-store',credentials:'same-origin',...(input?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}:{})});const data=await result.json();if(!result.ok){const error=new Error('Please try again.');error.status=result.status;throw error;}return data;}
  if(token){root.replaceChildren(make('h2','Stop VIZIMALL marketing emails'),make('p','Confirm below to withdraw this email subscription. This does not affect orders or customer support.'));const withdraw=button('Unsubscribe');const message=make('p');message.setAttribute('role','status');root.append(withdraw,message);withdraw.onclick=async()=>{withdraw.disabled=true;try{await request('newsletter-unsubscribe',{token});message.textContent='Your subscription is stopped. You will not be included in future VIZIMALL marketing exports.';}catch{message.textContent='We could not save the change. Please try again or contact info@vizimall.com.';withdraw.disabled=false;}};return;}
  async function load(){
    try{const data=await request('newsletter');root.replaceChildren(make('h2','Your email preferences'));const label=make('label','Verified email');const email=make('input');email.type='email';email.value=data.email;email.readOnly=true;label.append(email);root.append(label);
      const state=make('p',data.status==='subscribed'?'Subscribed to VIZIMALL news and offers.':'You are not subscribed.');root.append(state);const message=make('p');message.setAttribute('role','status');
      if(data.status==='subscribed'){const withdraw=button('Unsubscribe from email offers');root.append(withdraw,message);withdraw.onclick=async()=>{withdraw.disabled=true;try{await request('newsletter',{action:'unsubscribe'});await load();}catch{message.textContent='Could not save the change. Please try again.';withdraw.disabled=false;}};}
      else{const form=make('form');const consent=make('label');consent.className='newsletter-consent';const checkbox=make('input');checkbox.type='checkbox';checkbox.required=true;checkbox.checked=false;consent.append(checkbox,make('span',data.text));const submit=button('Subscribe to email updates');submit.type='submit';form.append(consent,submit,message);root.append(form);form.onsubmit=async event=>{event.preventDefault();if(!checkbox.checked)return;submit.disabled=true;try{await request('newsletter',{action:'subscribe',consent:true,version:data.version});await load();}catch{message.textContent='Your subscription was not saved. Please try again.';submit.disabled=false;}};}
    }catch(error){root.replaceChildren(make('h2',error.status===401?'Verify your email first':'Email preferences unavailable'));const login=make('a','Verify email / Sign in securely');login.className='account-button';login.href='/api/login?return=newsletter';root.append(make('p','Shopify sends a one-time code to your email. After sign-in, return here to choose whether to subscribe.'),login);}
  }load();
})();
